/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yatzy;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;




/**
 *
 * @author victorlells
 */
public class gamePage_JPanel extends javax.swing.JPanel {

    private int N = 4;
    private int prevN;
    private int reRoll = 0;
    static int numPlayers = 0;
    static String playerName[]  = new String[4];
    
    newDice Dice[] = {new newDice(167),new newDice(263),new newDice(359),new newDice(455),new newDice(551)};
    
    newPlayer[] Player = {new newPlayer(playerName[0]), new newPlayer(playerName[1]), 
                    new newPlayer(playerName[2]),new newPlayer(playerName[3]) }; 
    
    
    


    
    /**
     * Creates new form gamePage_JPanel
     */
    public gamePage_JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEttPar = new javax.swing.JButton();
        btnTvaPar = new javax.swing.JButton();
        btnTriss = new javax.swing.JButton();
        btnFyrtal = new javax.swing.JButton();
        btnLitenStege = new javax.swing.JButton();
        btnStorStege = new javax.swing.JButton();
        btnKak = new javax.swing.JButton();
        btnChans = new javax.swing.JButton();
        btnYatzy = new javax.swing.JButton();
        btnEttor = new javax.swing.JButton();
        btnTvaor = new javax.swing.JButton();
        btnTreor = new javax.swing.JButton();
        btnFyror = new javax.swing.JButton();
        btnFemmor = new javax.swing.JButton();
        btnSexor = new javax.swing.JButton();
        btnRullaTarn = new javax.swing.JButton();
        lblYatzy = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        lblEttPar = new javax.swing.JLabel();
        lblTvaPar = new javax.swing.JLabel();
        lblTriss = new javax.swing.JLabel();
        lblFyrtal = new javax.swing.JLabel();
        lblLitenStege = new javax.swing.JLabel();
        lblStorStege = new javax.swing.JLabel();
        lblKak = new javax.swing.JLabel();
        lblChans = new javax.swing.JLabel();
        lblYatzyScore = new javax.swing.JLabel();
        lblEttor = new javax.swing.JLabel();
        lblTvaor = new javax.swing.JLabel();
        lblTreor = new javax.swing.JLabel();
        lblFyror = new javax.swing.JLabel();
        lblFemmor = new javax.swing.JLabel();
        lblSexor = new javax.swing.JLabel();
        lblSumma = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        lblPoang = new javax.swing.JLabel();
        txfSumma = new javax.swing.JTextField();
        txfBonus = new javax.swing.JTextField();
        txfPoang = new javax.swing.JTextField();
        boxRe = new javax.swing.JCheckBox();
        boxRe1 = new javax.swing.JCheckBox();
        boxRe2 = new javax.swing.JCheckBox();
        boxRe3 = new javax.swing.JCheckBox();
        boxRe4 = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(660, 660));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        btnEttPar.setFont(new java.awt.Font("Bernard MT Condensed", 0, 24)); // NOI18N
        btnEttPar.setText("0");
        btnEttPar.setEnabled(false);
        btnEttPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEttParActionPerformed(evt);
            }
        });

        btnTvaPar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnTvaPar.setText("0");
        btnTvaPar.setEnabled(false);
        btnTvaPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTvaParActionPerformed(evt);
            }
        });

        btnTriss.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnTriss.setText("0");
        btnTriss.setEnabled(false);
        btnTriss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrissActionPerformed(evt);
            }
        });

        btnFyrtal.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnFyrtal.setText("0");
        btnFyrtal.setEnabled(false);
        btnFyrtal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFyrtalActionPerformed(evt);
            }
        });

        btnLitenStege.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnLitenStege.setText("0");
        btnLitenStege.setEnabled(false);
        btnLitenStege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLitenStegeActionPerformed(evt);
            }
        });

        btnStorStege.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnStorStege.setText("0");
        btnStorStege.setEnabled(false);
        btnStorStege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStorStegeActionPerformed(evt);
            }
        });

        btnKak.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnKak.setText("0");
        btnKak.setEnabled(false);
        btnKak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKakActionPerformed(evt);
            }
        });

        btnChans.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnChans.setText("0");
        btnChans.setEnabled(false);
        btnChans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChansActionPerformed(evt);
            }
        });

        btnYatzy.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnYatzy.setText("0");
        btnYatzy.setEnabled(false);
        btnYatzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYatzyActionPerformed(evt);
            }
        });

        btnEttor.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnEttor.setText("0");
        btnEttor.setEnabled(false);
        btnEttor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEttorActionPerformed(evt);
            }
        });

        btnTvaor.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnTvaor.setText("0");
        btnTvaor.setEnabled(false);
        btnTvaor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTvaorActionPerformed(evt);
            }
        });

        btnTreor.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnTreor.setText("0");
        btnTreor.setEnabled(false);
        btnTreor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreorActionPerformed(evt);
            }
        });

        btnFyror.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnFyror.setText("0");
        btnFyror.setEnabled(false);
        btnFyror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFyrorActionPerformed(evt);
            }
        });

        btnFemmor.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnFemmor.setText("0");
        btnFemmor.setEnabled(false);
        btnFemmor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemmorActionPerformed(evt);
            }
        });

        btnSexor.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnSexor.setText("0");
        btnSexor.setEnabled(false);
        btnSexor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSexorActionPerformed(evt);
            }
        });

        btnRullaTarn.setFont(new java.awt.Font("Trattatello", 0, 42)); // NOI18N
        btnRullaTarn.setText("ROLL DICE");
        btnRullaTarn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRullaTarnActionPerformed(evt);
            }
        });

        lblYatzy.setFont(new java.awt.Font("Trattatello", 0, 36)); // NOI18N
        lblYatzy.setText("YATZY!");

        lblPlayerName.setFont(new java.awt.Font("Trattatello", 0, 18)); // NOI18N
        lblPlayerName.setText("Player 1 | 0 Rerrols Left");

        lblEttPar.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblEttPar.setText("Ett Par:");

        lblTvaPar.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblTvaPar.setText("Två Par:");

        lblTriss.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblTriss.setText("Triss:");

        lblFyrtal.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblFyrtal.setText("Fyrtal:");

        lblLitenStege.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblLitenStege.setText("l, Stege:");

        lblStorStege.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblStorStege.setText("S, Stege:");

        lblKak.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblKak.setText("Kåk:");

        lblChans.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblChans.setText("Chans:");

        lblYatzyScore.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblYatzyScore.setText("Yatzy:");

        lblEttor.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblEttor.setText("Ettor:");

        lblTvaor.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblTvaor.setText("Tvåor:");

        lblTreor.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblTreor.setText("Treor:");

        lblFyror.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblFyror.setText("Fyror:");

        lblFemmor.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblFemmor.setText("Femmor:");

        lblSexor.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblSexor.setText("Sexor:");

        lblSumma.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblSumma.setText("Summa:");

        lblBonus.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblBonus.setText("Bonus:");

        lblPoang.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblPoang.setText("Poäng:");

        txfSumma.setEditable(false);
        txfSumma.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txfSumma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfSumma.setText("0");

        txfBonus.setEditable(false);
        txfBonus.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txfBonus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfBonus.setText("0");

        txfPoang.setEditable(false);
        txfPoang.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txfPoang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfPoang.setText("100");

        boxRe.setFont(new java.awt.Font("Trattatello", 0, 18)); // NOI18N
        boxRe.setText("Re-Roll?");

        boxRe1.setFont(new java.awt.Font("Trattatello", 0, 18)); // NOI18N
        boxRe1.setText("Re-Roll?");

        boxRe2.setFont(new java.awt.Font("Trattatello", 0, 18)); // NOI18N
        boxRe2.setText("Re-Roll?");

        boxRe3.setFont(new java.awt.Font("Trattatello", 0, 18)); // NOI18N
        boxRe3.setText("Re-Roll?");

        boxRe4.setFont(new java.awt.Font("Trattatello", 0, 18)); // NOI18N
        boxRe4.setText("Re-Roll?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRullaTarn, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblChans, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnChans, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblKak, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnKak, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblYatzyScore, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnYatzy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblStorStege, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnLitenStege, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLitenStege, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnStorStege, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFyrtal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnFyrtal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTriss, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnTriss, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTvaPar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnTvaPar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEttPar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnEttPar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txfBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPoang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfPoang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSumma, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txfSumma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEttor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnEttor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTvaor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnTvaor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTreor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnTreor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFyror, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnFyror, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFemmor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnFemmor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSexor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSexor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boxRe)
                .addGap(12, 12, 12)
                .addComponent(boxRe1)
                .addGap(18, 18, 18)
                .addComponent(boxRe2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxRe3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxRe4))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblYatzy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblYatzy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPlayerName)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxRe1)
                            .addComponent(boxRe2)
                            .addComponent(boxRe4)
                            .addComponent(boxRe3)
                            .addComponent(boxRe))
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEttPar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEttPar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTvaPar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTvaPar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTriss, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTriss, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFyrtal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFyrtal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLitenStege, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStorStege, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStorStege, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLitenStege, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEttor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEttor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTvaor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTvaor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTreor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTreor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFyror, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFyror, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFemmor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFemmor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSexor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChans, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChans, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYatzyScore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnYatzy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSumma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfSumma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfPoang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPoang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRullaTarn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void checkValues(){
        if(Player[N].getEttor() == 1){
            btnEttor.setEnabled(false);
            btnEttor.setText(Integer.toString(Player[N].getEttor()));
        }else{
            btnEttor.setEnabled(true);
            btnEttor.setText("0");
        }
        if(Player[N].getTvaor() == 2){
            btnTvaor.setEnabled(false);
            btnTvaor.setText(Integer.toString(Player[N].getTvaor()));
        }else{
            btnTvaor.setEnabled(true);
            btnTvaor.setText("0");
        }
        if(Player[N].getTreor() == 3){
            btnTreor.setEnabled(false);
            btnTreor.setText(Integer.toString(Player[N].getTreor()));
        }else{
            btnTreor.setEnabled(true);
            btnTreor.setText("0");
        }
        if(Player[N].getFyror() == 4){
            btnFyror.setEnabled(false);
            btnFyror.setText(Integer.toString(Player[N].getFyror()));
        }else{
            btnFyror.setEnabled(true);
            btnFyror.setText("0");
        }
        if(Player[N].getFemmor() == 5){
            btnFemmor.setEnabled(false);
            btnFemmor.setText(Integer.toString(Player[N].getFemmor()));
        }else{
            btnFemmor.setEnabled(true);
            btnFemmor.setText("0");
        }
        if(Player[N].getSexor() == 6){
            btnSexor.setEnabled(false);
            btnSexor.setText(Integer.toString(Player[N].getSexor()));
        }else{
            btnSexor.setEnabled(true);
            btnSexor.setText("0");
        }
        if(Player[N].getEttPar() > 0){
            btnEttPar.setEnabled(false);
            btnEttPar.setText(Integer.toString(Player[N].getEttPar()));
        }else{
            btnEttPar.setEnabled(true);
            btnEttPar.setText("0");
        }
        if(Player[N].getTvaPar() > 0){
            btnTvaPar.setEnabled(false);
            btnTvaPar.setText(Integer.toString(Player[N].getTvaPar()));
        }else{
            btnTvaPar.setEnabled(true);
            btnTvaPar.setText("0");
        }
        if(Player[N].getTriss() > 0){
            btnTriss.setEnabled(false);
            btnTriss.setText(Integer.toString(Player[N].getTriss()));
        }else{
            btnTriss.setEnabled(true);
            btnTriss.setText("0");
        }
        if(Player[N].getFyrtal() > 0){
            btnFyrtal.setEnabled(false);
            btnFyrtal.setText(Integer.toString(Player[N].getFyrtal()));
        }else{
            btnFyrtal.setEnabled(true);
            btnFyrtal.setText("0");
        }
        if(Player[N].getLitenStege() > 0){
            btnLitenStege.setEnabled(false);
            btnLitenStege.setText(Integer.toString(Player[N].getLitenStege()));
        }else{
            btnLitenStege.setEnabled(true);
            btnLitenStege.setText("0");
        }
        if(Player[N].getStorStege() > 0){
            btnStorStege.setEnabled(false);
            btnStorStege.setText(Integer.toString(Player[N].getStorStege()));
        }else{
            btnStorStege.setEnabled(true);
            btnStorStege.setText("0");
        }
        if(Player[N].getKak() > 0){
            btnKak.setEnabled(false);
            btnKak.setText(Integer.toString(Player[N].getKak()));
        }else{
            btnKak.setEnabled(true);
            btnKak.setText("0");
        }
        if(Player[N].getChans() > 0){
            btnChans.setEnabled(false);
            btnChans.setText(Integer.toString(Player[N].getChans()));
        }else{
            btnChans.setEnabled(true);
            btnChans.setText("0");
        }
        if(Player[N].getYatzy() > 0){
            btnYatzy.setEnabled(false);
            btnYatzy.setText(Integer.toString(Player[N].getYatzy()));
        }else{
            btnYatzy.setEnabled(true);
            btnYatzy.setText("0");
        }
        

    }
    
    private void updateScore(){
        
        txfSumma.setText(Integer.toString(Player[N].getEttor()+ Player[N].getTvaor()+  
        Player[N].getTreor()+ Player[N].getFyror()+  Player[N].getFemmor()+ Player[N].getSexor()));
        
        if( Integer.valueOf(txfSumma.getText()) >= 63)
        {
            txfBonus.setText("50");
        }
        
        txfPoang.setText(Integer.toString(Integer.valueOf(txfSumma.getText()) + 
                Player[N].getEttPar() + Player[N].getTvaPar() + Player[N].getTriss() +
                Player[N].getFyrtal() + Player[N].getLitenStege() + Player[N].getStorStege() +
                Player[N].getKak() + Player[N].getChans() + Player[N].getYatzy()));
    
    }
    
    private void checkDice(){
        for (int i = 0; i <= 4; i++){
          if(Dice[i].getVarde() == 1){
              btnEttor.setEnabled(true);
          }if(Dice[i].getVarde() == 2){
              btnTvaor.setEnabled(true);
          }if(Dice[i].getVarde() == 3){
              btnTreor.setEnabled(true);
          }if(Dice[i].getVarde() == 4){
              btnFyror.setEnabled(true);
          }if(Dice[i].getVarde() == 5){
              btnFemmor.setEnabled(true);
          }if(Dice[i].getVarde() == 6){
              btnSexor.setEnabled(true);
          }
        }
    
    }
    
    private void btnRullaTarnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRullaTarnActionPerformed

        if(reRoll == 0){ 
            
            prevN = N;
            
            if (N < numPlayers){
                N = N + 1;  
            }else if (N >= numPlayers){
                N = 0;
            }
            
            if(prevN != N){
                boxRe.setSelected(false);
                boxRe1.setSelected(false);
                boxRe2.setSelected(false);
                boxRe3.setSelected(false);
                boxRe4.setSelected(false);
            }
            
            checkValues();
            updateScore();
            checkDice();
            
            for (int i= 0; i<=4 ; i++){
                Dice[i].setVarde();
                System.out.println("1");
            }
            
            reRoll = 3;
            lblPlayerName.setText(Player[N].getNamn()+" | 3 Rerolls left");
    
        }else if(reRoll>0){
            
            if(boxRe.isSelected()){
                Dice[0].setVarde();
            }
            if(boxRe1.isSelected()){
                Dice[1].setVarde();
            }
            if(boxRe2.isSelected()){
                Dice[2].setVarde();
            }
            if(boxRe3.isSelected()){
                Dice[3].setVarde();
            }
            if(boxRe4.isSelected()){
                Dice[4].setVarde();
            }
            
            reRoll -= 1;
            lblPlayerName.setText( Player[N].getNamn() +" | 0 Rerolls left");
        }
        if(reRoll == 2){
            
            lblPlayerName.setText( Player[N].getNamn() +" | 2 Rerolls left");
        
        }if(reRoll == 1){
           
            lblPlayerName.setText( Player[N].getNamn() +" | 1 Rerolls left");
        
        }
        repaint();
    }//GEN-LAST:event_btnRullaTarnActionPerformed

    private void btnEttParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEttParActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEttParActionPerformed

    private void btnTvaParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTvaParActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTvaParActionPerformed

    private void btnTrissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrissActionPerformed

    private void btnFyrtalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFyrtalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFyrtalActionPerformed

    private void btnStorStegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStorStegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStorStegeActionPerformed

    private void btnLitenStegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLitenStegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLitenStegeActionPerformed

    private void btnKakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKakActionPerformed

    private void btnChansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChansActionPerformed

    private void btnYatzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYatzyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYatzyActionPerformed

    private void btnEttorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEttorActionPerformed
        for (int i = 0; i <=4; i++){
            if(Dice[i].getVarde() == 1){
              Player[N].setEttor(Player[N].getEttor() + 1);
              btnEttor.setEnabled(false);
            }
        }
        btnEttor.setText(Integer.toString(Player[N].getEttor()));
        updateScore();
    }//GEN-LAST:event_btnEttorActionPerformed

    private void btnTvaorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTvaorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTvaorActionPerformed

    private void btnTreorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTreorActionPerformed

    private void btnFyrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFyrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFyrorActionPerformed

    private void btnFemmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemmorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFemmorActionPerformed

    private void btnSexorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSexorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSexorActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown
    
    public void paintComponent(Graphics g)
    {   
        System.out.println("3");
        super.paintComponent(g);
        
            for (int i= 0; i<=4 ; i++){
                int x = Dice[i].getX();
                switch (Dice[i].getVarde()) {
                    case 1:
                        g.setColor(Color.darkGray);
                        g.fillRect(x, 18, 86, 86);
                        g.setColor(Color.white);
                        g.fillOval(x+30, 48, 26, 26);
                        break;
                    case 2:
                        g.setColor(Color.darkGray);
                        g.fillRect(x, 18, 86, 86);
                        g.setColor(Color.white);
                        g.fillOval(x+1, 19, 26, 26);
                        g.fillOval(x+59, 77, 26, 26);
                        break;
                    case 3:
                        g.setColor(Color.darkGray);
                        g.fillRect(x, 18, 86, 86);
                        g.setColor(Color.white);
                        g.fillOval(x+1, 19, 26, 26);
                        g.fillOval(x+30, 48, 26, 26);
                        g.fillOval(x+59, 77, 26, 26);
                        break;
                    case 4:
                        g.setColor(Color.darkGray);
                        g.fillRect(x, 18, 86, 86);
                        g.setColor(Color.white);
                        g.fillOval(x+1, 19, 26, 26);
                        g.fillOval(x+59, 19, 26, 26);
                        g.fillOval(x+59, 77, 26, 26);
                        g.fillOval(x+1, 77, 26, 26);
                        break;
                    case 5:
                        g.setColor(Color.darkGray);
                        g.fillRect(x+1, 19, 86, 86);
                        g.setColor(Color.white);
                        g.fillOval(x+1, 19, 26, 26);
                        g.fillOval(x+59, 19, 26, 26);
                        g.fillOval(x+30, 48, 26, 26);
                        g.fillOval(x+59, 77, 26, 26);
                        g.fillOval(x+1, 77, 26, 26);
                        break;
                    case 6:
                        g.setColor(Color.darkGray);
                        g.fillRect(x, 18, 86, 86);
                        g.setColor(Color.white);
                        g.fillOval(x+1, 19, 26, 26);
                        g.fillOval(x+59, 19, 26, 26);
                        g.fillOval(x+30, 19, 26, 26);
                        g.fillOval(x+30, 77, 26, 26);
                        g.fillOval(x+59, 77, 26, 26);
                        g.fillOval(x+1, 77, 26, 26);
                        break;
                }
            }  
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxRe;
    private javax.swing.JCheckBox boxRe1;
    private javax.swing.JCheckBox boxRe2;
    private javax.swing.JCheckBox boxRe3;
    private javax.swing.JCheckBox boxRe4;
    private javax.swing.JButton btnChans;
    private javax.swing.JButton btnEttPar;
    private javax.swing.JButton btnEttor;
    private javax.swing.JButton btnFemmor;
    private javax.swing.JButton btnFyror;
    private javax.swing.JButton btnFyrtal;
    private javax.swing.JButton btnKak;
    private javax.swing.JButton btnLitenStege;
    private javax.swing.JButton btnRullaTarn;
    private javax.swing.JButton btnSexor;
    private javax.swing.JButton btnStorStege;
    private javax.swing.JButton btnTreor;
    private javax.swing.JButton btnTriss;
    private javax.swing.JButton btnTvaPar;
    private javax.swing.JButton btnTvaor;
    private javax.swing.JButton btnYatzy;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblChans;
    private javax.swing.JLabel lblEttPar;
    private javax.swing.JLabel lblEttor;
    private javax.swing.JLabel lblFemmor;
    private javax.swing.JLabel lblFyror;
    private javax.swing.JLabel lblFyrtal;
    private javax.swing.JLabel lblKak;
    private javax.swing.JLabel lblLitenStege;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPoang;
    private javax.swing.JLabel lblSexor;
    private javax.swing.JLabel lblStorStege;
    private javax.swing.JLabel lblSumma;
    private javax.swing.JLabel lblTreor;
    private javax.swing.JLabel lblTriss;
    private javax.swing.JLabel lblTvaPar;
    private javax.swing.JLabel lblTvaor;
    private javax.swing.JLabel lblYatzy;
    private javax.swing.JLabel lblYatzyScore;
    private javax.swing.JTextField txfBonus;
    private javax.swing.JTextField txfPoang;
    private javax.swing.JTextField txfSumma;
    // End of variables declaration//GEN-END:variables
}
