/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yatzy;



/**
 *
 * @author victorlells
 */
public class Scores_JFrame extends javax.swing.JFrame {

    
    static String playerName[] = new String[4];
    static int playerScore[] = new int[4];
    static int numPlayers = 0;
    
    /**
     * Creates new form Scores_JFrame
     */
    public Scores_JFrame() {
        initComponents();
        scorePrint(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblScore2 = new javax.swing.JLabel();
        lblScore4 = new javax.swing.JLabel();
        lblScore3 = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lblPlace1 = new javax.swing.JLabel();
        lblPlace2 = new javax.swing.JLabel();
        lblPlace3 = new javax.swing.JLabel();
        lblPlace4 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        lblPlayer4 = new javax.swing.JLabel();
        lblPlayer3 = new javax.swing.JLabel();
        lblPlayer1 = new javax.swing.JLabel();
        lblScore1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblScore2.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblScore2.setText("123");

        lblScore4.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblScore4.setText("123");

        lblScore3.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblScore3.setText("123");

        btnRestart.setFont(new java.awt.Font("Trattatello", 0, 36)); // NOI18N
        btnRestart.setText("Restart");
        btnRestart.setSize(new java.awt.Dimension(150, 50));
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        btnQuit.setFont(new java.awt.Font("Trattatello", 0, 36)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setSize(new java.awt.Dimension(150, 50));
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        lblPlace1.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblPlace1.setForeground(new java.awt.Color(0, 200, 0));
        lblPlace1.setText("1st:");

        lblPlace2.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblPlace2.setText("2nd:");

        lblPlace3.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblPlace3.setText("3rd:");

        lblPlace4.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblPlace4.setText("4th:");

        lblPlayer2.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer2.setText("Player 1");

        lblPlayer4.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblPlayer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer4.setText("Player 1");

        lblPlayer3.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblPlayer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer3.setText("Player 1");

        lblPlayer1.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblPlayer1.setForeground(new java.awt.Color(0, 200, 0));
        lblPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer1.setText("Player 1");

        lblScore1.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        lblScore1.setForeground(new java.awt.Color(0, 200, 0));
        lblScore1.setText("123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlace1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(lblPlayer1)
                                .addGap(50, 50, 50)
                                .addComponent(lblScore1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlace2)
                                .addGap(50, 50, 50)
                                .addComponent(lblPlayer2)
                                .addGap(50, 50, 50)
                                .addComponent(lblScore2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPlace4)
                                    .addComponent(lblPlace3))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPlayer3)
                                        .addGap(50, 50, 50)
                                        .addComponent(lblScore3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, 0)
                                        .addComponent(lblPlayer4)
                                        .addGap(50, 50, 50)
                                        .addComponent(lblScore4))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlace1)
                    .addComponent(lblPlayer1)
                    .addComponent(lblScore1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlace2)
                    .addComponent(lblPlayer2)
                    .addComponent(lblScore2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlace3)
                    .addComponent(lblPlayer3)
                    .addComponent(lblScore3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlace4)
                    .addComponent(lblPlayer4)
                    .addComponent(lblScore4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        new mainPage_JFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed
    
    
    private void scorePrint(){
        switch (numPlayers){
            case 0:
                
                lblPlayer1.setText(playerName[0]);
                lblScore1.setText(Integer.toString(playerScore[0]));
                
                lblPlace2.setVisible(false);
                lblPlace3.setVisible(false);
                lblPlace4.setVisible(false);
                lblPlayer2.setVisible(false);
                lblPlayer4.setVisible(false);
                lblPlayer3.setVisible(false);
                lblScore2.setVisible(false);
                lblScore4.setVisible(false);
                lblScore3.setVisible(false);
                
                break;
                
            case 1:
                
                lblPlayer1.setText(playerName[1]);
                lblScore1.setText(Integer.toString(playerScore[1]));
                lblPlayer2.setText(playerName[0]);
                lblScore2.setText(Integer.toString(playerScore[0]));
                


                lblPlace3.setVisible(false);
                lblPlace4.setVisible(false);
                lblPlayer4.setVisible(false);
                lblPlayer3.setVisible(false);
                lblScore4.setVisible(false);
                lblScore3.setVisible(false);
                
                
                    break;
            case 2:
                
                lblPlayer1.setText(playerName[2]);
                lblScore1.setText(Integer.toString(playerScore[2]));
                lblPlayer2.setText(playerName[1]);
                lblScore2.setText(Integer.toString(playerScore[1]));
                lblPlayer4.setText(playerName[0]);
                lblScore4.setText(Integer.toString(playerScore[0]));

                
                lblPlace4.setVisible(false);
                lblPlayer3.setVisible(false);
                lblScore3.setVisible(false);
                
                    break;
            case 3:
                
                lblPlayer1.setText(playerName[3]);
                lblScore1.setText(Integer.toString(playerScore[3]));
                lblPlayer2.setText(playerName[2]);
                lblScore2.setText(Integer.toString(playerScore[2]));
                lblPlayer4.setText(playerName[0]);
                lblScore4.setText(Integer.toString(playerScore[0]));
                lblPlayer3.setText(playerName[1]);
                lblScore3.setText(Integer.toString(playerScore[1]));
                    break;
                
         
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scores_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scores_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scores_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scores_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scores_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel lblPlace1;
    private javax.swing.JLabel lblPlace2;
    private javax.swing.JLabel lblPlace3;
    private javax.swing.JLabel lblPlace4;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblPlayer3;
    private javax.swing.JLabel lblPlayer4;
    private javax.swing.JLabel lblScore1;
    private javax.swing.JLabel lblScore2;
    private javax.swing.JLabel lblScore3;
    private javax.swing.JLabel lblScore4;
    // End of variables declaration//GEN-END:variables
}
